In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
%matplotlib inline

In [5]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [6]:
train.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL           65     8450   Pave   NaN      Reg   
1   2          20       RL           80     9600   Pave   NaN      Reg   
2   3          60       RL           68    11250   Pave   NaN      IR1   
3   4          70       RL           60     9550   Pave   NaN      IR1   
4   5          60       RL           84    14260   Pave   NaN      IR1   

  LandContour Utilities    ...     PoolArea PoolQC Fence MiscFeature MiscVal  \
0         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
1         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
2         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
3         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
4         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   

  MoSold YrSold  SaleType  SaleCondition  SalePrice  
0      2   2008        WD         Normal     208500  
1      5   2007        WD         Normal     181500  
2      9   2008        WD         Normal     223500  
3      2   2006        WD        Abnorml     140000  
4     12   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [7]:
test.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0  1461          20       RH           80    11622   Pave   NaN      Reg   
1  1462          20       RL           81    14267   Pave   NaN      IR1   
2  1463          60       RL           74    13830   Pave   NaN      IR1   
3  1464          60       RL           78     9978   Pave   NaN      IR1   
4  1465         120       RL           43     5005   Pave   NaN      IR1   

  LandContour Utilities      ...       ScreenPorch PoolArea PoolQC  Fence  \
0         Lvl    AllPub      ...               120        0    NaN  MnPrv   
1         Lvl    AllPub      ...                 0        0    NaN    NaN   
2         Lvl    AllPub      ...                 0        0    NaN  MnPrv   
3         Lvl    AllPub      ...                 0        0    NaN    NaN   
4         HLS    AllPub      ...               144        0    NaN    NaN   

  MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition  
0         NaN       0      6    2010        WD         Normal  
1        Gar2   12500      6    2010        WD         Normal  
2         NaN       0      3    2010        WD         Normal  
3         NaN       0      6    2010        WD         Normal  
4         NaN       0      1    2010        WD         Normal  

[5 rows x 80 columns]

In [8]:
train.shape

(1460, 81)

In [9]:
#81 rows and 1460 columns
#let's apply basic linear regression using simple 5 features.
#Let's look at description of dataset.

In [10]:
col_x = ['MSZoning','LotArea','LotShape','HouseStyle']

In [11]:
x = train[col_x]
x_test = test[col_x]

In [12]:
x.head()

MSZoning  LotArea LotShape HouseStyle
0       RL     8450      Reg     2Story
1       RL     9600      Reg     1Story
2       RL    11250      IR1     2Story
3       RL     9550      IR1     2Story
4       RL    14260      IR1     2Story

In [13]:
x_test.head()

MSZoning  LotArea LotShape HouseStyle
0       RH    11622      Reg     1Story
1       RL    14267      IR1     1Story
2       RL    13830      IR1     2Story
3       RL     9978      IR1     2Story
4       RL     5005      IR1     1Story

In [14]:
#let's plot some charts and see how above features affect SalePrice

In [15]:
# plt.plot(kind='scatter',x='LotArea',y='SalePrice')
import seaborn as sns

In [16]:
sns.set

<function seaborn.rcmod.set>

In [17]:
x.LotShape.value_counts()

Reg    925
IR1    484
IR2     41
IR3     10
Name: LotShape, dtype: int64

In [18]:
x.LotShape.isnull().sum()

0

In [19]:
x.MSZoning.value_counts()

RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: MSZoning, dtype: int64

In [20]:
x.HouseStyle.value_counts()

1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
1.5Unf     14
2.5Unf     11
2.5Fin      8
Name: HouseStyle, dtype: int64

In [21]:
#Let's analyze more about how various features are distributed.

In [22]:
#Let's map all features to numbers.

In [23]:
zone_map = {"RL":0,"RM":1,"FV":2,"RH":3,"C (all)":4}

In [24]:
# for dataset in x:
#     dataset['MSZoning'] = dataset['MSZoning'].map(zone_map) 

In [25]:
x.MSZoning = x.MSZoning.apply(lambda c:zone_map[c])

/usr/lib/python2.7/dist-packages/pandas/core/generic.py:2387: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value


In [26]:
x.head()

MSZoning  LotArea LotShape HouseStyle
0         0     8450      Reg     2Story
1         0     9600      Reg     1Story
2         0    11250      IR1     2Story
3         0     9550      IR1     2Story
4         0    14260      IR1     2Story

In [27]:
lotshape_map = {"Reg":0,"IR1":1,"IR2":2,"IR3":3}

In [28]:
x.LotShape = x.LotShape.apply(lambda c:lotshape_map[c])

In [29]:
hstyle_map = {"1Story":0,"2Story":2,"1.5Fin":3,"SLvl":4,"SFoyer":5,"1.5Unf":6,"2.5Unf":7,"2.5Fin":8}

In [30]:
x.HouseStyle = x.HouseStyle.apply(lambda c:hstyle_map[c])

In [31]:
x.head()

MSZoning  LotArea  LotShape  HouseStyle
0         0     8450         0           2
1         0     9600         0           0
2         0    11250         1           2
3         0     9550         1           2
4         0    14260         1           2

In [32]:
#Now that we have handled all features we have taken for calculating price.

y = train.SalePrice
y.head()

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64

In [33]:
# drop_feature = ['SalePrice']

In [34]:
# x = x.drop(drop_feature,axis=1)

In [35]:
x.head()

MSZoning  LotArea  LotShape  HouseStyle
0         0     8450         0           2
1         0     9600         0           0
2         0    11250         1           2
3         0     9550         1           2
4         0    14260         1           2

In [36]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [37]:
lr = LinearRegression()

In [38]:
lr.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [39]:
x_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1459 entries, 0 to 1458
Data columns (total 4 columns):
MSZoning      1455 non-null object
LotArea       1459 non-null int64
LotShape      1459 non-null object
HouseStyle    1459 non-null object
dtypes: int64(1), object(3)
memory usage: 57.0+ KB


In [40]:
import random

In [41]:
x_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1459 entries, 0 to 1458
Data columns (total 4 columns):
MSZoning      1455 non-null object
LotArea       1459 non-null int64
LotShape      1459 non-null object
HouseStyle    1459 non-null object
dtypes: int64(1), object(3)
memory usage: 57.0+ KB


In [42]:
x_test[ x_test['MSZoning'].isnull() ]

MSZoning  LotArea LotShape HouseStyle
455       NaN    21780      Reg     1Story
756       NaN    14584      Reg     1Story
790       NaN    56600      IR1     2.5Unf
1444      NaN    31250      Reg     1Story

In [43]:
x_test.shape

(1459, 4)

In [44]:
x [ x.HouseStyle == 0].head()

MSZoning  LotArea  LotShape  HouseStyle
1          0     9600         0           0
6          0    10084         0           0
10         0    11200         0           0
12         0    12968         2           0
13         0    10652         1           0

In [45]:
x_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1459 entries, 0 to 1458
Data columns (total 4 columns):
MSZoning      1455 non-null object
LotArea       1459 non-null int64
LotShape      1459 non-null object
HouseStyle    1459 non-null object
dtypes: int64(1), object(3)
memory usage: 57.0+ KB


In [46]:
x_test['MSZoning'] = x_test['MSZoning'].fillna('RL')


/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [47]:
x_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1459 entries, 0 to 1458
Data columns (total 4 columns):
MSZoning      1459 non-null object
LotArea       1459 non-null int64
LotShape      1459 non-null object
HouseStyle    1459 non-null object
dtypes: int64(1), object(3)
memory usage: 57.0+ KB


In [48]:
x_test.head()

MSZoning  LotArea LotShape HouseStyle
0       RH    11622      Reg     1Story
1       RL    14267      IR1     1Story
2       RL    13830      IR1     2Story
3       RL     9978      IR1     2Story
4       RL     5005      IR1     1Story

In [49]:
x_test.MSZoning = x_test.MSZoning.apply(lambda c:zone_map[c])

In [50]:
x_test.head()

MSZoning  LotArea LotShape HouseStyle
0         3    11622      Reg     1Story
1         0    14267      IR1     1Story
2         0    13830      IR1     2Story
3         0     9978      IR1     2Story
4         0     5005      IR1     1Story

In [51]:
x_test.LotShape = x_test.LotShape.apply(lambda c:lotshape_map[c])

In [52]:
x_test.head()

MSZoning  LotArea  LotShape HouseStyle
0         3    11622         0     1Story
1         0    14267         1     1Story
2         0    13830         1     2Story
3         0     9978         1     2Story
4         0     5005         1     1Story

In [53]:
x_test.HouseStyle = x_test.HouseStyle.apply(lambda c:hstyle_map[c])

In [54]:
x_test.head()

MSZoning  LotArea  LotShape  HouseStyle
0         3    11622         0           0
1         0    14267         1           0
2         0    13830         1           2
3         0     9978         1           2
4         0     5005         1           0

In [55]:
y_pred = lr.predict(x_test)

In [56]:
x_test.head()

MSZoning  LotArea  LotShape  HouseStyle
0         3    11622         0           0
1         0    14267         1           0
2         0    13830         1           2
3         0     9978         1           2
4         0     5005         1           0

In [57]:
y_pred

array([ 136348.85619149,  206828.59808898,  204451.73428379, ...,
        189820.37509215,  171369.85480446,  172764.11925277])

In [58]:
lr.coef_

array([ -1.36979692e+04,   1.47739453e+00,   2.54781258e+04,
        -8.65621198e+02])

In [59]:
y_pred

array([ 136348.85619149,  206828.59808898,  204451.73428379, ...,
        189820.37509215,  171369.85480446,  172764.11925277])

In [68]:
my_submission = pd.DataFrame({'Id': test.Id, 'SalePrice': y_pred})
# you could use any filename. We choose submission here
my_submission.to_csv('submission.csv', index=False)

In [69]:
my_submission.head()

Id      SalePrice
0  1461  136348.856191
1  1462  206828.598089
2  1463  204451.734284
3  1464  198760.810560
4  1465  193144.969967